apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "monitor.fullname" . }}
  labels:
    app: {{ template "monitor.name" . }}
    chart: {{ template "monitor.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  revisionHistoryLimit: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "monitor.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "monitor.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
      annotations:
        buildID: {{ .Values.buildID | default "" | quote }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.deployment.ports }}
            - name: {{ .name }}
              containerPort: {{ .containerPort }}
            {{- end }}
          {{- if .Values.volumeBinding.enabled }}
          volumeMounts:
{{ toYaml .Values.volumeBinding.volumeMounts | indent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
{{ toYaml .Values.livenessProbe.value | indent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          readinessProbe:
{{ toYaml .Values.readinessProbe.value | indent 12 }}
          {{- end }}
          env:
{{ toYaml .Values.env | indent 12 }}
          command:
{{ toYaml .Values.command | indent 12 }}
          args:
{{ toYaml .Values.args | indent 12 }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.volumeBinding.enabled }}
      volumes:
{{ toYaml .Values.volumeBinding.volumes | indent 8 }}
    {{- end }}
