{{- $root := . }}
{{- range $name, $values := .Values.dockerconfigjsonSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
data:
  {{- range $key, $value := $values }}
  {{ $key }}: {{ $value }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
---
{{- end }}
