apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ template "monitor.name" . }}
    chart: {{ template "monitor.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- if .Values.service.headless }}
  clusterIP: "None"
{{- end }}
  ports:
   {{- range .Values.service.ports }}
    - port:  {{ .port }}
{{- if .isNodePort }}
      nodePort: {{ .nodePort }}
{{- end }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
   {{- end }}
  selector:
    app: {{ template "monitor.name" . }}
    release: {{ .Release.Name }}
